const About = ()=>{

    return(<>
    <div ><h1>about</h1> Proin auctor lacus nibh, eu placerat felis semper ac. Integer ac laoreet ipsum. Nam mi leo, suscipit quis dui ut, blandit faucibus massa. Proin at orci tempus massa fringilla rhoncus. Nulla facilisi. Vestibulum ut fermentum tortor. Proin faucibus, tellus nec tincidunt mollis, lacus ipsum tristique felis, vitae pellentesque leo dui quis neque. Curabitur efficitur, nisl vitae feugiat posuere, ligula enim ullamcorper eros, non tempus orci libero in odio. Morbi quis interdum orci, in efficitur diam. Suspendisse potenti. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec urna ac orci fringilla scelerisque. Proin metus dolor, pulvinar eu nibh a, dapibus scelerisque ligula. Sed laoreet mauris eget nulla tincidunt, consectetur imperdiet urna accumsan. Nulla facilisi.

Suspendisse sit amet hendrerit dolor. Praesent ut ligula nunc. Aenean lobortis mauris et suscipit commodo. Sed nec ipsum et nunc posuere condimentum. Etiam egestas egestas augue mollis rhoncus. Duis eleifend mi laoreet augue euismod euismod. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce ullamcorper egestas dictum. Curabitur dignissim posuere pulvinar. Pellentesque tincidunt, purus ac molestie mattis, diam augue vehicula ipsum, sit amet faucibus odio lacus vitae lectus. Sed quis consequat nisi. Donec neque tortor, condimentum vel porta nec, tincidunt eget purus. Suspendisse finibus elementum dui ornare volutpat. Sed sagittis ex sed maximus accumsan. Nullam tortor sem, hendrerit vitae condimentum et, vehicula sed elit. Aliquam gravida aliquet maximus.

Sed dui ante, faucibus et consequat nec, cursus ac ligula. Maecenas porttitor, lacus a gravida ornare, mi eros congue nibh, molestie tempor lorem eros quis sem. Nullam in quam laoreet, elementum nisi eget, tempus sem. Nullam et sollicitudin urna. Fusce consectetur urna a quam maximus pulvinar a ac neque. In eget accumsan quam, et interdum diam. Etiam nec nisl eu tellus faucibus molestie. Etiam gravida consectetur nulla quis congue. Nullam erat lectus, tincidunt sit amet iaculis et, molestie quis orci. Pellentesque facilisis dolor sed nunc venenatis, id mattis erat hendrerit. Proin tincidunt bibendum sapien malesuada pulvinar. Proin pellentesque pulvinar ipsum, quis tempor felis viverra id. Sed et nulla varius, rutrum turpis sed, venenatis ex. Quisque interdum elementum ante, non sagittis diam dapibus</div>
    </>)
}
export default About